# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb3f45557bcb2edc401419ab6f7dda1ce59e933f308c32c3a2b044265923abee97eb5240c08fc036de462379e3afcb75ebf0b20c66046bfcca074b6f897e12e9

test:
  secret_key_base: f4d38327e7bd0e8fbc4c25e6bc340037489fdca1a04d078c577731e46a114b33e0143a1d5fa6fa8c27279e01f90d6bef60233506b0684d252829c0033095ce5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
